package com.server.backend.service.Implant;
import com.server.backend.DTO.Implant.ImplantReportResponse;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import com.server.backend.DTO.Implant.ImplantCreateRequest;
import com.server.backend.entity.Placements.ImplantEntity;
import com.server.backend.DTO.Implant.ImplantResponse;
import com.server.backend.DTO.Implant.InplantDashboardResponse;
import com.server.backend.Repository.PlacementsRepositories.ImplantRepository;
import com.server.backend.Repository.PlacementsRepositories.IndustriesRepository;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
@Service
public class ImplantServiceImpl implements ImplantService {

    private final JdbcTemplate jdbcTemplate;
    private final ImplantRepository implantRepository;
    private  final IndustriesRepository industriesRepository;
    public ImplantServiceImpl(JdbcTemplate jdbcTemplate, ImplantRepository implantRepository, IndustriesRepository industriesRepository) {
        this.jdbcTemplate = jdbcTemplate;
        this.implantRepository = implantRepository;
        this.industriesRepository = industriesRepository;
    }

    @Override
    public InplantDashboardResponse getInplantDashboardDetails() {
        InplantDashboardResponse response = new InplantDashboardResponse();

        response.setInplantTotal(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM implant.implant", Long.class));
        response.setInplantDistinctItis(jdbcTemplate.queryForObject("SELECT COUNT(DISTINCT iti_code) FROM implant.implant", Long.class));
        response.setInplantDistinctSlnos(jdbcTemplate.queryForObject("SELECT COUNT(DISTINCT slno) FROM implant.implant", Long.class));

        response.setIndustriesTotal(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM implant.industries", Long.class));
        response.setIndustriesDistinctItis(jdbcTemplate.queryForObject("SELECT COUNT(DISTINCT iti_code) FROM implant.industries", Long.class));
        response.setIndustriesDistinctIndustries(jdbcTemplate.queryForObject("SELECT COUNT(DISTINCT industry_id) FROM implant.industries", Long.class));
        response.setIndustriesDistinctTrades(jdbcTemplate.queryForObject("SELECT COUNT(DISTINCT trade_code) FROM implant.industries", Long.class));

        response.setIndustryMasterTotal(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM implant.industry_master", Long.class));
        response.setIndustryMasterMajor(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM implant.industry_master WHERE industry_type = 'Major'", Long.class));
        response.setIndustryMasterMinor(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM implant.industry_master WHERE industry_type = 'Minor'", Long.class));

        response.setSumOfStudent(jdbcTemplate.queryForObject("SELECT COALESCE(SUM(no_of_students), 0) FROM implant.implant", Long.class));

        return response;
    }
  @Override
public ImplantResponse createImplant(ImplantCreateRequest request) {

    ImplantEntity implant = new ImplantEntity();

    implant.setDescription(request.getDescription());
    implant.setDistCode(request.getDistcode());
    implant.setFacultyName(request.getFacultyName());
    implant.setFromDate(request.getFromDate());
    implant.setHrNo(request.getHrNo());
    implant.setIndustryAddress(request.getIndustryAddress());
    implant.setItiCode(request.getItiCode());
    implant.setLocation(request.getLocation());
    implant.setNoOfDays(request.getNoOfDays());
    implant.setNoOfStudents(request.getNoOfStudents());
    implant.setToDate(request.getToDate());
    implant.setTradeShort(request.getTradeShort());
    implant.setEntryBy(request.getEntryBy());

    // Generated by backends
    implant.setEntryDate(LocalDateTime.now());

    ImplantEntity savedImplant = implantRepository.save(implant);

    return mapToImplantResponse(savedImplant);
}

    @Override
    public List<ImplantResponse> getAllImplants() {

        return implantRepository.findAll()
                .stream()
                .map(this::mapToImplantResponse)
                .toList();
    }

    @Override
    public ImplantResponse getImplantById(Long implantId) {

        ImplantEntity implant = implantRepository.findById(implantId)
                .orElseThrow(() ->
                        new RuntimeException("In-Plant record not found with ID: " + implantId)
                );

        return mapToImplantResponse(implant);
    }
@Override
    public ImplantResponse updateImplant(Long implantId, ImplantCreateRequest request) {

    ImplantEntity implant = implantRepository.findById(implantId)
            .orElseThrow(() ->
                    new RuntimeException("In-Plant record not found with ID: " + implantId)
            );

    implant.setDescription(request.getDescription());
    implant.setDistCode(request.getDistcode());
    implant.setFacultyName(request.getFacultyName());
    implant.setFromDate(request.getFromDate());
    implant.setHrNo(request.getHrNo());
    implant.setIndustryAddress(request.getIndustryAddress());
    implant.setItiCode(request.getItiCode());
    implant.setLocation(request.getLocation());
    implant.setNoOfDays(request.getNoOfDays());
    implant.setNoOfStudents(request.getNoOfStudents());
    implant.setToDate(request.getToDate());
    implant.setTradeShort(request.getTradeShort());
    implant.setEntryBy(request.getEntryBy());

    
    ImplantEntity updatedImplant = implantRepository.save(implant);

    return mapToImplantResponse(updatedImplant);
}
 @Override
public void deleteImplant(Long implantId) {

    ImplantEntity implant = implantRepository.findById(implantId)
            .orElseThrow(() ->
                    new RuntimeException("In-Plant record not found with ID: " + implantId)
            );

    implantRepository.delete(implant);
}

   private ImplantResponse mapToImplantResponse(ImplantEntity implant) {

    ImplantResponse response = new ImplantResponse();

    response.setImplantId(implant.getImplantId());
    response.setDescription(implant.getDescription());
    response.setDistcode(implant.getDistCode());
    response.setEntryDate(implant.getEntryDate());
    response.setFacultyName(implant.getFacultyName());
    response.setFromDate(implant.getFromDate());
    response.setHrNo(implant.getHrNo());
    response.setIndustryAddress(implant.getIndustryAddress());
    response.setItiCode(implant.getItiCode());
    response.setLocation(implant.getLocation());
    response.setNoOfDays(implant.getNoOfDays());
    response.setNoOfStudents(implant.getNoOfStudents());
    response.setSlno(implant.getSlno());
    response.setToDate(implant.getToDate());
    response.setTradeShort(implant.getTradeShort());
    response.setEntryBy(implant.getEntryBy());

    return response;
}
 @Override
    public List<Object[]> getItis() {
        return industriesRepository.getItis();
    }

    @Override
    public List<Object[]> getIndustries(Integer itiCode) {
        return industriesRepository.getIndustries(itiCode);
    }
    
     
    @Override
public List<ImplantReportResponse> getReport(String itiCode) {

    List<Object[]> rows = implantRepository.getReportData(itiCode);

    List<ImplantReportResponse> response = new ArrayList<>();

    for (Object[] row : rows) {

        ImplantReportResponse dto = new ImplantReportResponse();

        dto.setImplantId(((Number) row[0]).longValue());
dto.setItiName((String) row[1]);
dto.setIndustryName((String) row[2]);
dto.setFacultyName((String) row[3]);
dto.setTradeName((String) row[4]);

dto.setIndustryAddress((String) row[5]);
dto.setHrNo(row[6] == null ? null : ((Number) row[6]).longValue());
dto.setFromDate((LocalDate) row[7]);
dto.setToDate((LocalDate) row[8]);
dto.setNoOfDays(row[9] == null ? null : ((Number) row[9]).intValue());
dto.setNoOfStudents(row[10] == null ? null : ((Number) row[10]).intValue());
dto.setStateName((String) row[11]);
dto.setDistrictName((String) row[12]);
dto.setLocation((String) row[13]);
dto.setDescription((String) row[14]);
        response.add(dto);
    }

    return response;
}

    @Override
    public List<Object[]> getDistrictItis(String distCode) {
        String sql = "SELECT iti_code, iti_name FROM public.iti WHERE dist_code = ? ORDER BY iti_name";
        return jdbcTemplate.queryForList(sql, distCode).stream()
                .map(m -> new Object[]{m.get("iti_code"), m.get("iti_name")})
                .toList();
    }

    @Override
    public List<ImplantReportResponse> getDistrictReport(String itiCode, Integer industryId) {
        StringBuilder sql = new StringBuilder();
        List<Object> params = new ArrayList<>();
        sql.append("""
            SELECT
                i.implant_id,
                it.iti_name,
                ind.industry_name,
                i.faculty_name,
                ind.trade_name,
                i.industry_address,
                i.hr_no,
                i.from_date,
                i.to_date,
                i.no_of_days,
                i.no_of_students,
                sm.statename,
                dm.dist_name,
                i.location,
                i.description
            FROM implant.implant i
            JOIN implant.industries ind
                ON CAST(i.iti_code AS INTEGER) = ind.iti_code
               AND i.trade_short = ind.trade_short
            LEFT JOIN public.iti it
                ON CAST(i.iti_code AS INTEGER) = it.iti_code
            LEFT JOIN public2.dist_mst dm
                ON it.dist_code = dm.dist_code
            LEFT JOIN public.states_mast sm
                ON dm.statecode = sm.statecode
            WHERE 1=1
        """);
        if (itiCode != null && !itiCode.isBlank()) {
            sql.append(" AND i.iti_code = ? ");
            params.add(itiCode);
        }
        if (industryId != null) {
            sql.append(" AND ind.industry_id = ? ");
            params.add(industryId);
        }
        sql.append(" ORDER BY i.implant_id ");

        List<Object[]> rows = jdbcTemplate.query(sql.toString(), params.toArray(), (rs, rowNum) -> {
            Object[] row = new Object[15];
            row[0] = rs.getLong("implant_id");
            row[1] = rs.getString("iti_name");
            row[2] = rs.getString("industry_name");
            row[3] = rs.getString("faculty_name");
            row[4] = rs.getString("trade_name");
            row[5] = rs.getString("industry_address");
            row[6] = rs.getObject("hr_no");
            row[7] = rs.getObject("from_date");
            row[8] = rs.getObject("to_date");
            row[9] = rs.getObject("no_of_days");
            row[10] = rs.getObject("no_of_students");
            row[11] = rs.getString("statename");
            row[12] = rs.getString("dist_name");
            row[13] = rs.getString("location");
            row[14] = rs.getString("description");
            return row;
        });

        List<ImplantReportResponse> response = new ArrayList<>();
        for (Object[] row : rows) {
            ImplantReportResponse dto = new ImplantReportResponse();
            dto.setImplantId(((Number) row[0]).longValue());
            dto.setItiName((String) row[1]);
            dto.setIndustryName((String) row[2]);
            dto.setFacultyName((String) row[3]);
            dto.setTradeName((String) row[4]);
            dto.setIndustryAddress((String) row[5]);
            dto.setHrNo(row[6] == null ? null : ((Number) row[6]).longValue());
            dto.setFromDate(row[7] == null ? null : ((java.sql.Date) row[7]).toLocalDate());
            dto.setToDate(row[8] == null ? null : ((java.sql.Date) row[8]).toLocalDate());
            dto.setNoOfDays(row[9] == null ? null : ((Number) row[9]).intValue());
            dto.setNoOfStudents(row[10] == null ? null : ((Number) row[10]).intValue());
            dto.setStateName((String) row[11]);
            dto.setDistrictName((String) row[12]);
            dto.setLocation((String) row[13]);
            dto.setDescription((String) row[14]);
            response.add(dto);
        }
        return response;
    }
}
