package com.server.backend.service.Implant;
import com.server.backend.DTO.Implant.ImplantReportResponse;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import com.server.backend.DTO.Implant.ImplantCreateRequest;
import com.server.backend.entity.Placements.ImplantEntity;
import com.server.backend.DTO.Implant.ImplantResponse;
import com.server.backend.DTO.Implant.InplantDashboardResponse;
import com.server.backend.Repository.PlacementsRepositories.ImplantRepository;
import com.server.backend.Repository.PlacementsRepositories.IndustriesRepository;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
@Service
public class ImplantServiceImpl implements ImplantService {

    private final JdbcTemplate jdbcTemplate;
    private final ImplantRepository implantRepository;
    private  final IndustriesRepository industriesRepository;
    public ImplantServiceImpl(JdbcTemplate jdbcTemplate, ImplantRepository implantRepository, IndustriesRepository industriesRepository) {
        this.jdbcTemplate = jdbcTemplate;
        this.implantRepository = implantRepository;
        this.industriesRepository = industriesRepository;
    }

    @Override
    public InplantDashboardResponse getInplantDashboardDetails() {
        InplantDashboardResponse response = new InplantDashboardResponse();

        response.setInplantTotal(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM implant.implant", Long.class));
        response.setInplantDistinctItis(jdbcTemplate.queryForObject("SELECT COUNT(DISTINCT iti_code) FROM implant.implant", Long.class));
        response.setInplantDistinctSlnos(jdbcTemplate.queryForObject("SELECT COUNT(DISTINCT slno) FROM implant.implant", Long.class));

        response.setIndustriesTotal(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM implant.industries", Long.class));
        response.setIndustriesDistinctItis(jdbcTemplate.queryForObject("SELECT COUNT(DISTINCT iti_code) FROM implant.industries", Long.class));
        response.setIndustriesDistinctIndustries(jdbcTemplate.queryForObject("SELECT COUNT(DISTINCT industry_id) FROM implant.industries", Long.class));
        response.setIndustriesDistinctTrades(jdbcTemplate.queryForObject("SELECT COUNT(DISTINCT trade_code) FROM implant.industries", Long.class));

        response.setIndustryMasterTotal(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM implant.industry_master", Long.class));
        response.setIndustryMasterMajor(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM implant.industry_master WHERE industry_type = 'Major'", Long.class));
        response.setIndustryMasterMinor(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM implant.industry_master WHERE industry_type = 'Minor'", Long.class));

        response.setSumOfStudent(jdbcTemplate.queryForObject("SELECT COALESCE(SUM(no_of_students), 0) FROM implant.implant", Long.class));

        return response;
    }
  @Override
public ImplantResponse createImplant(ImplantCreateRequest request) {

    ImplantEntity implant = new ImplantEntity();

    implant.setDescription(request.getDescription());
    implant.setDistCode(request.getDistcode());
    implant.setFacultyName(request.getFacultyName());
    implant.setFromDate(request.getFromDate());
    implant.setHrNo(request.getHrNo());
    implant.setIndustryAddress(request.getIndustryAddress());
    implant.setItiCode(request.getItiCode());
    implant.setLocation(request.getLocation());
    implant.setNoOfDays(request.getNoOfDays());
    implant.setNoOfStudents(request.getNoOfStudents());
    implant.setToDate(request.getToDate());
    implant.setTradeShort(request.getTradeShort());
    implant.setEntryBy(request.getEntryBy());

    // Generated by backends
    implant.setEntryDate(LocalDateTime.now());

    ImplantEntity savedImplant = implantRepository.save(implant);

    return mapToImplantResponse(savedImplant);
}

    @Override
    public List<ImplantResponse> getAllImplants() {

        return implantRepository.findAll()
                .stream()
                .map(this::mapToImplantResponse)
                .toList();
    }

    @Override
    public ImplantResponse getImplantById(Long implantId) {

        ImplantEntity implant = implantRepository.findById(implantId)
                .orElseThrow(() ->
                        new RuntimeException("In-Plant record not found with ID: " + implantId)
                );

        return mapToImplantResponse(implant);
    }
@Override
    public ImplantResponse updateImplant(Long implantId, ImplantCreateRequest request) {

    ImplantEntity implant = implantRepository.findById(implantId)
            .orElseThrow(() ->
                    new RuntimeException("In-Plant record not found with ID: " + implantId)
            );

    implant.setDescription(request.getDescription());
    implant.setDistCode(request.getDistcode());
    implant.setFacultyName(request.getFacultyName());
    implant.setFromDate(request.getFromDate());
    implant.setHrNo(request.getHrNo());
    implant.setIndustryAddress(request.getIndustryAddress());
    implant.setItiCode(request.getItiCode());
    implant.setLocation(request.getLocation());
    implant.setNoOfDays(request.getNoOfDays());
    implant.setNoOfStudents(request.getNoOfStudents());
    implant.setToDate(request.getToDate());
    implant.setTradeShort(request.getTradeShort());
    implant.setEntryBy(request.getEntryBy());

    
    ImplantEntity updatedImplant = implantRepository.save(implant);

    return mapToImplantResponse(updatedImplant);
}
 @Override
public void deleteImplant(Long implantId) {

    ImplantEntity implant = implantRepository.findById(implantId)
            .orElseThrow(() ->
                    new RuntimeException("In-Plant record not found with ID: " + implantId)
            );

    implantRepository.delete(implant);
}

   private ImplantResponse mapToImplantResponse(ImplantEntity implant) {

    ImplantResponse response = new ImplantResponse();

    response.setImplantId(implant.getImplantId());
    response.setDescription(implant.getDescription());
    response.setDistcode(implant.getDistCode());
    response.setEntryDate(implant.getEntryDate());
    response.setFacultyName(implant.getFacultyName());
    response.setFromDate(implant.getFromDate());
    response.setHrNo(implant.getHrNo());
    response.setIndustryAddress(implant.getIndustryAddress());
    response.setItiCode(implant.getItiCode());
    response.setLocation(implant.getLocation());
    response.setNoOfDays(implant.getNoOfDays());
    response.setNoOfStudents(implant.getNoOfStudents());
    response.setSlno(implant.getSlno());
    response.setToDate(implant.getToDate());
    response.setTradeShort(implant.getTradeShort());
    response.setEntryBy(implant.getEntryBy());

    return response;
}
 @Override
    public List<Object[]> getItis() {
        return industriesRepository.getItis();
    }

    @Override
    public List<Object[]> getIndustries(Integer itiCode) {
        return industriesRepository.getIndustries(itiCode);
    }
    
     
    @Override
public List<ImplantReportResponse> getReport(String itiCode) {

    List<Object[]> rows = implantRepository.getReportData(itiCode);

    List<ImplantReportResponse> response = new ArrayList<>();

    for (Object[] row : rows) {

        ImplantReportResponse dto = new ImplantReportResponse();

        dto.setImplantId(((Number) row[0]).longValue());
dto.setItiName((String) row[1]);
dto.setIndustryName((String) row[2]);
dto.setFacultyName((String) row[3]);
dto.setTradeName((String) row[4]);

dto.setIndustryAddress((String) row[5]);
dto.setHrNo(row[6] == null ? null : ((Number) row[6]).longValue());
dto.setFromDate((LocalDate) row[7]);
dto.setToDate((LocalDate) row[8]);
dto.setNoOfDays(row[9] == null ? null : ((Number) row[9]).intValue());
dto.setNoOfStudents(row[10] == null ? null : ((Number) row[10]).intValue());
dto.setStateName((String) row[11]);
dto.setDistrictName((String) row[12]);
dto.setLocation((String) row[13]);
dto.setDescription((String) row[14]);
        response.add(dto);
    }

    return response;
}
}


