package com.server.backend.service.Implant;

import com.server.backend.DTO.Implant.IndustryTradeMappingRequest;
import com.server.backend.entity.Placements.Industries;
import com.server.backend.entity.Placements.IndustryMaster;
import com.server.backend.Repository.PlacementsRepositories.IndustriesRepository;
import com.server.backend.Repository.PlacementsRepositories.IndustryMasterRepository;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.sql.Timestamp;

@Service
public class IndustryTradeMappingServiceImpl
        implements IndustryTradeMappingService {

    private final IndustriesRepository industriesRepository;
    private final IndustryMasterRepository industryMasterRepository;

    public IndustryTradeMappingServiceImpl(
            IndustriesRepository industriesRepository,
            IndustryMasterRepository industryMasterRepository) {

        this.industriesRepository = industriesRepository;
        this.industryMasterRepository = industryMasterRepository;
    }

    @Override
    @Transactional
    public String saveIndustryTradeMapping(
            IndustryTradeMappingRequest request) {

        // 1. Validate request
        if (request.getItiCode() == null) {
            throw new RuntimeException("ITI code is required");
        }

        if (request.getIndustryId() == null) {
            throw new RuntimeException("Industry ID is required");
        }

        if (request.getTradeCode() == null) {
            throw new RuntimeException("Trade code is required");
        }

        // 2. Check duplicate mapping
        boolean alreadyExists =
                industriesRepository
                        .existsByItiCodeAndIndustryIdAndTradeCode(
                                request.getItiCode(),
                                request.getIndustryId(),
                                request.getTradeCode()
                        );

        if (alreadyExists) {
            throw new RuntimeException(
                    "This industry and trade is already mapped to this ITI"
            );
        }

        // 3. Get industry master information
        IndustryMaster industryMaster =
                industryMasterRepository
                        .findById(request.getIndustryId())
                        .orElseThrow(() ->
                                new RuntimeException(
                                        "Industry not found: "
                                                + request.getIndustryId()
                                )
                        );

        // 4. Create mapping
        Industries mapping = new Industries();

        // slno is generated by PostgreSQL sequence
        mapping.setItiCode(request.getItiCode());

        mapping.setIndustryId(
                industryMaster.getIndustryId()
        );

        mapping.setIndustryName(
                industryMaster.getIndustryName()
        );

        mapping.setIndustryType(
                industryMaster.getIndustryType()
        );

        mapping.setTradeCode(
                request.getTradeCode()
        );

        mapping.setTradeName(
                request.getTradeName()
        );

        mapping.setTradeShort(
                request.getTradeShort()
        );

        mapping.setEntryTime(
                new Timestamp(System.currentTimeMillis())
        );

        // 5. Save
        industriesRepository.save(mapping);

        return "Industry and trade mapped successfully";
    }
}